
unit_name_to_tag <- function(v, units) {
	out <- units$unit_tag[units$unit_name == v]
	if (length(out) == 0) {
		info(paste0("No unit tag found for unit: ", v))
	}
	return(out)
}

translate_unit_path_to_tags <- function(v, units) {
	v_tags <- 
		v %>%
		gsub(" (Primary Output Unit)", "", ., fixed = TRUE) %>%
		strsplit(., split = "\\\\rightarrow") %>%
		unlist %>%
		trimws %>%
		lapply(unit_name_to_tag, units = units) %>% 
		unlist
	if (all(is.na(v_tags))) {
		v_tags <- ""
	} 
	if (length(v_tags) > 1)
		v_tags <- paste(v_tags, collapse = ",")
	stopifnot(length(v_tags) == 1)
	return(v_tags)
}


#' @title Create methodology document
#' @description Create a pdf document with the methodology of the Demscore project.
#' @param REFDIR Path to the directory with the static files (intro.tex etc.).
#' @param temp_dir Path to the directory where temporary files are stored.
#' @param ROOT_DIR Path to the root directory of the Demscore project.
#' @param INDIR Path to the directory with the prepped postgres tables.
#' @param outfile Path to the output file.
#' @export
create_methodology <- function(
	REFDIR = file.path("~/proj/demscore/reference_documents/demscoremethodology"),
	temp_dir = tempdir(check = TRUE),
	ROOT_DIR = Sys.getenv("ROOT_DIR"),
	INDIR = file.path(ROOT_DIR, "autogenerated_refs", "refs"),
	outfile = file.path("~/proj/demscore/reference_documents/demscoremethodology/methodology.pdf")) {

	download_refs()

	# Read template file
	intro <- readLines(file.path(REFDIR, "intro.tex"), encoding = "UTF-8")
	outro <- readLines(file.path(REFDIR, "outro.tex"), encoding = "UTF-8")

	# Read variable information
	stopifnot(`You need a file with the methodology table!` = 
		file.exists(file.path(INDIR, "methodology.rds")))
	units <- vbase::read_file(file.path(INDIR, "units.rds"))
	unit_trans <- vbase::read_file(file.path(INDIR, "unit_trans.rds"))
	datasets <- vbase::read_file(file.path(INDIR, "datasets.rds"))
	methodology <- vbase::read_file(file.path(INDIR, "methodology.rds"))
	projects <- vbase::read_file(file.path(INDIR, "projects.rds"))

	methodology <- methodology[methodology$show, , drop = FALSE]

	# Generate methodology path codes
	# in order to later merge with unit_trans table.
	methodology$translation_path_codes <-
		lapply(methodology$translation_path, 
			   translate_unit_path_to_tags, 
			   units = units) %>% 
		unlist

	methodology$additional_info[!is.na(methodology$additional_info)] <- 
		paste0(" \n \\textbf{Additional information:} \n", 
			methodology$additional_info[!is.na(methodology$additional_info)])

	# Overwrite description with information from unit_trans table
	# trans_description and from methodology column additional_info.

	

	# Bug detection:
	# v <- methodology %>% filter(unit_tag == "u_hdata_minister_date",
	# 	dataset_tag == "vdem_cd") %$% translation_path
	# with(methodology,
	# 	which(unit_tag == "u_hdata_minister_date" &
	# 		dataset_tag == "vdem_cd"))
	methodology$description <- lapply(methodology$translation_path_codes,
		function(v) {
			# v <- methodology$translation_path_codes[284]
			if (v == "")
				return("")
			ll <- strsplit(v, split = ",") %>% unlist
			stopifnot(length(ll) > 0)

			if (length(ll) > 1) {
				pairs <- data.frame(start = ll[1:(length(ll) - 1)],
								end = ll[2:length(ll)])
		
				# Loop over pairs
				outtext <- lapply(1:nrow(pairs), function(i){
					# i <- 1
				
					introtext <- paste0(
						"\\textbf{", units$unit_name[units$unit_tag == pairs$start[i]], 
						" Unit to ",
						units$unit_name[units$unit_tag == pairs$end[i]], 
						" Unit translation} \n",
						unit_trans$trans_description[
							unit_trans$start == pairs$start[i] &
							unit_trans$finish == pairs$end[i]],
						"\n")
				}) %>% paste(., collapse = "")

			} else {
				# primary unit only
				outtext <- paste0(units$unit_name[units$unit_tag == ll], 
					" is the primary unit.")
			}

			outtext <- gsub("[\n]+$", "", outtext)
			return(outtext)
		}) %>% unlist

	# Paste additional_info into description
	methodology$description[!is.na(methodology$additional_info)] <- 
		paste0(methodology$description[!is.na(methodology$additional_info)], 
			methodology$additional_info[!is.na(methodology$additional_info)])

	# Debugging
	# methodology %>% filter(grepl("H-DATA Minister-Date is the primary unit.",
	# 	description)) %$% description %>% print

	methodology$description <- 
		paste0("\\textbf{Translation Path: ", 
			gsub("\\\\rightarrow", "$\\\\rightarrow$", methodology$translation_path), 
			"} \n",
			methodology$description)

	projects %<>%
		dplyr::mutate(., cb_entry = gsub("\n", "\\vspace{0.3cm}\\\\\n\\noindent ", cb_entry, fixed = TRUE)) %>%
		dplyr::arrange(., project_short) %>%
		dplyr::mutate(., cb_entry = paste0("\\subsection{", cb_title, "}", "\n\\noindent ", cb_entry))

	# Define list of tex to fill whisker with.
	tex_list <- list()
	tex_list$project_tex <- paste(projects$cb_entry, collapse = "\n")

	# Dataset entries
	datasets %<>% 
		dplyr::mutate(., cb_entry  = gsub("\n", "\\\\\\\\\n", cb_entry)) %>%
		dplyr::mutate(., ds_unit_explanations = 
			gsub("\n", "\\\\\\\\\n", ds_unit_explanations)) %>%
		dplyr::arrange(., tag) %>%
		dplyr::filter(., grepl(Sys.getenv("DEMSCORE_RELEASE"), demscore_release))
	
	# tex_list$dataset_tex <- 
	# 	paste("\\subsection{", datasets$name, "}", "\n\\noindent ", 
	# 		datasets$cb_entry, "\n", collapse = "\n")

	# Output units section
	units %<>% 
		dplyr::mutate(., cb_unit_entry  = gsub("\n", "\\\\\\\\\n", cb_unit_entry)) %>%
		dplyr::arrange(., unit_tag) %>%
		dplyr::filter(., active) %>%
		dplyr::select(., -active)
	tex_list$unit_tex <- 
		paste("\\subsection{", units$unit_name %^% " Unit", "}", "\n\\noindent ", 
			units$cb_unit_entry, "\n", collapse = "\n")

	# Methodology table
	methodology %<>% 
		# Remove \\ from description entry
		dplyr::mutate(., description = gsub("\\\\\\\\", "", description)) %>%
		dplyr::mutate(., description = gsub("\n", "\\vspace{0.3cm}\\\\\n\\noindent ", description, fixed = TRUE)) %>%
		dplyr::filter(., show) %>%
		dplyr::select(., -show) %>%
		dplyr::arrange(., dataset_tag, ordering)

	# Dataset-Output unit combinations
	df_ <- 
		dplyr::inner_join(methodology, 
			  dplyr::select(units, unit_id, unit_name), 
			  by = "unit_id") %>%
		dplyr::left_join(., 
			dplyr::select(datasets, dataset_id, dataset_name = name, ds_unit_explanations,
						  ds_cb_entry = cb_entry), 
			by = "dataset_id") %>%
		dplyr::arrange(., dataset_tag, unit_tag)

	df_ %<>%
		dplyr::group_by(., dataset_tag, unit_name) %>%
		dplyr::summarize(., 
			dataset_name = first(dataset_name),
			ds_cb_entry = first(ds_cb_entry),
			ds_unit_explanations = first(ds_unit_explanations),
			ordering = first(ordering),
			cb_entry = 
				paste("\\subsubsection{", unit_name %^% " Unit", "}", "\n", "\\noindent ",
			  description, "\n", collapse = "\n")) %>%
		dplyr::group_by(., dataset_tag) %>%
		dplyr::arrange(., ordering, unit_name) %>%
		dplyr::summarize(., 
			dataset_name = first(dataset_name),
			ds_cb_entry = first(ds_cb_entry),
			ds_unit_explanations = first(ds_unit_explanations),
			cb_entry = paste0(cb_entry, collapse = "\n")) %>%
		dplyr::mutate(., cb_entry = paste0(
			"\\newpage \\subsection{", dataset_name, "}", "\n",
			"\\noindent", ds_cb_entry, "\n",
			"\n\\vspace{0.3cm}\\noindent\\textbf{Unit Notes:} \n", 
			ds_unit_explanations, "\n", cb_entry))

	tex_list$ds_unit_tex <- paste(df_$cb_entry, collapse = "\n")


	outtex <- whisker::whisker.render(intro, tex_list)
	# Attach outro
	outtex <- c(outtex, outro)

	# replace \n with \n\\ in the whole tex file?

	# dir.create("build", showWarnings = FALSE)
	writeLines(outtex, file.path(temp_dir, "method.tex"))

	# Copy methodrefs.bib
	file.copy(file.path(REFDIR, "methodrefs.bib"), 
			  file.path(temp_dir, "methodrefs.bib"), overwrite = TRUE)

	# Copy pdf cover page
	file.copy(file.path(REFDIR, "methodologyfrontpage.pdf"),
		file.path(temp_dir, "methodologyfrontpage.pdf"), overwrite = TRUE)
	
	tex_file <- file.path(temp_dir, "method.tex")
	
	system("latexmk -cd -f -jobname=methodology " %^%
	         "-pdf -pdflatex='pdflatex -interaction=nonstopmode' " %^%
	         tex_file)
	
	system("latexmk -cd -f -g -jobname=methodology " %^%
	         "-pdf -pdflatex='pdflatex -interaction=nonstopmode' " %^%
	         tex_file)
	
	file.copy(
	  file.path(temp_dir, "methodology.pdf"),
	  outfile,
	  overwrite = TRUE)
	
}
