#' @title Download references from database
#' @description Downloads the references from the database and saves them to
#' a prespecified directory. These files are later used for dataset and
#' codebook generation.
#' @param ROOT_DIR The root directory of the project.
#' @param OUTDIR The directory to save the references to.
#' @param db The database connection.
#' @return Returns NULL invisibly.
#' @export
download_refs <- function(
	ROOT_DIR = Sys.getenv("ROOT_DIR"), 
	OUTDIR = file.path(ROOT_DIR, "autogenerated_refs", "refs"), 
	db = pg_connect()) {

		# Download
	citations <- dplyr::tbl(db, "citations") %>% dplyr::collect(n = Inf)
	datasets <- dplyr::tbl(db, "datasets") %>% dplyr::collect(n = Inf)
	variables <- dplyr::tbl(db, "variables") %>% dplyr::collect(n = Inf)
	units <- dplyr::tbl(db, "units") %>% dplyr::collect(n = Inf)
	unit_trans <- dplyr::tbl(db, "unit_trans") %>% dplyr::collect(n = Inf)
	methodology <- dplyr::tbl(db, "methodology") %>% dplyr::collect(n = Inf)
	cb_section <- dplyr::tbl(db, "cb_section") %>% dplyr::collect(n = Inf)
	projects <- dplyr::tbl(db, "projects") %>% dplyr::collect(n = Inf)
	codebook <- dplyr::tbl(db, "codebook") %>% dplyr::collect(n = Inf)
	unit_variables <- dplyr::tbl(db, "unit_variables") %>% dplyr::collect(n = Inf)
	thematic_datasets <- dplyr::tbl(db, "thematic_datasets") %>% dplyr::collect(n = Inf)
	thematic_datasets_variables <- dplyr::tbl(db, "thematic_datasets_variables") %>% 
		dplyr::collect(n = Inf)
	merge_scores <- dplyr::tbl(db, "merge_scores") %>% dplyr::collect(n = Inf)


	# Write files
	vbase::write_file(variables, file.path(OUTDIR, "variables.rds"), dir_create = TRUE)
	vbase::write_file(datasets, file.path(OUTDIR, "datasets.rds"))
	vbase::write_file(units, file.path(OUTDIR, "units.rds"))
	vbase::write_file(methodology, file.path(OUTDIR, "methodology.rds"))
	vbase::write_file(cb_section, file.path(OUTDIR, "cb_section.rds"))
	vbase::write_file(projects, file.path(OUTDIR, "projects.rds"))
	vbase::write_file(codebook, file.path(OUTDIR, "codebook.rds"))
	vbase::write_file(unit_variables, file.path(OUTDIR, "unit_variables.rds"))
	vbase::write_file(unit_trans, file.path(OUTDIR, "unit_trans.rds"))
	vbase::write_file(citations, file.path(OUTDIR, "citations.rds"))
	vbase::write_file(thematic_datasets, file.path(OUTDIR, "thematic_datasets.rds"))
	vbase::write_file(thematic_datasets_variables, 
		file.path(OUTDIR, "thematic_datasets_variables.rds"))
	vbase::write_file(merge_scores, file.path(OUTDIR, "merge_scores.rds"))
	return(invisible(NULL))
}

#' @title copy static reference files
#' @description Copies the static reference files to the autogenerated_refs
#' directory.
#' @param ROOT_DIR The root directory of the project.
#' @param REFS_DIR The directory containing the static reference files.
#' @param REFS_OUT_DIR The directory to save the references to.
#' @return Returns NULL invisibly.
copy_static_refs <- function(
	ROOT_DIR = Sys.getenv("ROOT_DIR"), 
	REFS_DIR = file.path("~/proj/demscore/reference_documents"), 
	REFS_OUT_DIR = file.path(ROOT_DIR, "autogenerated_refs", "static")) {

	# Copy static files
	dir.create(REFS_OUT_DIR, showWarnings = FALSE, recursive = TRUE)
	file.copy(file.path(REFS_DIR, "demscorecodebook", "intro.tex"),
			  file.path(REFS_OUT_DIR, "intro.tex"), overwrite = TRUE)
	file.copy(file.path(REFS_DIR, "demscorecodebook", "outro.tex"),
			  file.path(REFS_OUT_DIR, "outro.tex"), overwrite = TRUE)
	file.copy(file.path(REFS_DIR, "demscorecodebook", "variable_template.tex"),
			  file.path(REFS_OUT_DIR, "variable_template.tex"), overwrite = TRUE)
	file.copy(file.path(REFS_DIR, "demscorecodebook", "codebookfrontpage.pdf"),
			  file.path(REFS_OUT_DIR, "codebookfrontpage.pdf"), overwrite = TRUE)
	return(invisible(NULL))
}

#' @title Prepare references
#' @description Prepares the references for use in the autogenerated codebook and dataset
#' @param ROOT_DIR The root directory of the project.
#' @param INDIR The directory containing the reference files.
#' @param OUTDIR The directory to save the references to.
prepare_refs <- function(
	ROOT_DIR = Sys.getenv("ROOT_DIR"),
	INDIR = file.path(ROOT_DIR, "autogenerated_refs", "refs"),
	OUTDIR = file.path(ROOT_DIR, "autogenerated_refs", "refs_prepped")) {

	# Read tables
	cb_section <- vbase::read_file(file.path(INDIR, "cb_section.rds"))
	codebook <- vbase::read_file(file.path(INDIR, "codebook.rds"))
	datasets <- vbase::read_file(file.path(INDIR, "datasets.rds"))
	methodology <- vbase::read_file(file.path(INDIR, "methodology.rds"))
	projects <- vbase::read_file(file.path(INDIR, "projects.rds"))
	units <- vbase::read_file(file.path(INDIR, "units.rds"))
	unit_variables <- vbase::read_file(file.path(INDIR, "unit_variables.rds"))
	variables <- vbase::read_file(file.path(INDIR, "variables.rds"))
	variables_tbl <- variables
	citations <- vbase::read_file(file.path(INDIR, "citations.rds"))
	thematic_datasets <- vbase::read_file(file.path(INDIR, "thematic_datasets.rds"))
	thematic_datasets_variables <- 
		vbase::read_file(file.path(INDIR, "thematic_datasets_variables.rds"))
	merge_scores <- vbase::read_file(file.path(INDIR, "merge_scores.rds"))

	# Create labels table for data STATA file
	df_labels <- variables %>% dplyr::select(tag_long, label = name)
	df_labels_unit_variables <- dplyr::select(unit_variables, 
		tag_long = tag, 
		label = name)
	df_labels <- dplyr::bind_rows(df_labels, df_labels_unit_variables)

	# Filter active rows
	datasets %<>%
		dplyr::filter(grepl(Sys.getenv("DEMSCORE_RELEASE"), demscore_release))
	methodology %<>% dplyr::filter(show)
	units %<>% dplyr::filter(active)
	variables %<>% dplyr::filter(cb_show)

	# Merge tables
	#unit_variables %<>%
	#	dplyr::left_join(dplyr::select(codebook, codebook_id, cb_entry), by = "codebook_id")

	# Use citations table for variable and dataset citations
	variables %<>% 
		dplyr::select(-citation) %>% 
		dplyr::left_join(dplyr::select(citations, citation_id, citation_short, bibtex), 
			  by = "citation_id") %>%
		dplyr::rename(citation = citation_short)

	datasets %<>%
		dplyr::select(-dataset_citation) %>%
		dplyr::left_join(dplyr::select(citations, citation_id, citation_short, bibtex), 
			  by = "citation_id") %>%
		dplyr::rename(dataset_citation = citation_short,
			   dataset_bibtex = bibtex)


	# variables table (df) for download interface
	# We join variables and datasets table and clean the data a bit so this does not 
	# have to happen later on during the automatic codebook generation.
	# We want to do as much pre-processing as possible so it goes faster 
	# to later create the codebook.
	df_variables <- 
		variables %>%
		dplyr::inner_join(
			dplyr::select(datasets, dataset_id, project_short, dataset_citation, 
						  dataset_tag = tag, dataset_bibtex), 
			by = "dataset_id") %>%
		dplyr::left_join(dplyr::select(codebook, codebook_id, cb_entry), by = "codebook_id") %>%
		dplyr::mutate(cb_entry = gsub("[", "{[}", cb_entry, fixed = TRUE)) %>%
		dplyr::mutate(cb_entry = gsub("]", "{]}", cb_entry, fixed = TRUE)) %>%
		# Replace \\`space`\n with \\\n
		dplyr::mutate(cb_entry = gsub("\\\\\\\\[[:blank:]]\n", "\\\\\\\\\n", cb_entry)) %>%
		# Every occurence of \n that is not preceded by \\ is replaced with \\\n
		dplyr::mutate(cb_entry = gsub("(?<!\\\\\\\\)\n", "\\\\\\\\\n", cb_entry, perl = TRUE)) %>%
		# Escape & symbol with \&
		dplyr::mutate(cb_entry = gsub("&", "\\&", cb_entry, fixed = TRUE)) %>%
		dplyr::mutate(citation = gsub("&", "\\&", citation, fixed = TRUE)) %>%
		dplyr::mutate(name = gsub("&", "\\&", name, fixed = TRUE)) %>%
		# Replace percentage sign % with percent
		dplyr::mutate(cb_entry = gsub("%", "percent", cb_entry, fixed = TRUE)) %>%
		dplyr::mutate(cb_entry = gsub("\\percent", "percent", cb_entry, fixed = TRUE)) %>%
		dplyr::mutate(name = gsub("%", "percent", name, fixed = TRUE)) %>%
		dplyr::mutate(name = gsub("\\percent", "percent", name, fixed = TRUE)) %>%
		# Replace ~ with \textasciitilde
		dplyr::mutate(cb_entry = gsub("~", "\\textasciitilde", cb_entry, fixed = TRUE)) %>%
		dplyr::mutate(name = gsub("~", "\\textasciitilde", name, fixed = TRUE)) %>%
		dplyr::mutate(citation = gsub("~", "\\textasciitilde", citation, fixed = TRUE))

	# For QoG replace \href with \url
	# This may not be needed anymore when we use the citations table!
	df_variables$citation[df_variables$project_short == "qog"] <- 
		gsub("\\href", "\\url", 
			 df_variables$citation[df_variables$project_short == "qog"], 
			 fixed = TRUE)


	head_var_children <- 
		variables_tbl %>%
		dplyr::arrange(variable_id) %>%
		dplyr::select(head_var, tag_long) %>%
		dplyr::filter(!is.na(head_var)) %>%
		dplyr::mutate(head_var_children_id = 1:nrow(.))

	head_var_parents <- 
		variables_tbl %>%
		dplyr::arrange(variable_id) %>%
		dplyr::select(head_var = tag_long) %>%
		dplyr::filter(head_var %in% head_var_children$head_var) %>%
		dplyr::mutate(head_var_parents_id = 1:nrow(.))

	df_dataset_selection <- prep_dataset_selection(methodology, datasets, units)
	df_selection <- prep_selection(variables, methodology, ROOT_DIR, cb_section, datasets, units)
	



	# Write files
	vbase::write_file(cb_section, file.path(OUTDIR, "cb_section.rds"), dir_create = TRUE)
	vbase::write_file(codebook, file.path(OUTDIR, "codebook.rds"))
	vbase::write_file(citations, file.path(OUTDIR, "citations.rds"))
	vbase::write_file(datasets, file.path(OUTDIR, "datasets.rds"))
	vbase::write_file(units, file.path(OUTDIR, "units.rds"))
	vbase::write_file(methodology, file.path(OUTDIR, "methodology.rds"))
	vbase::write_file(projects, file.path(OUTDIR, "projects.rds"))
	vbase::write_file(unit_variables, file.path(OUTDIR, "unit_variables.rds"))
	vbase::write_file(df_variables, file.path(OUTDIR, "variables.rds"))
	vbase::write_file(df_labels, file.path(OUTDIR, "labels.rds"))
	vbase::write_file(thematic_datasets, file.path(OUTDIR, "thematic_datasets.rds"))
	vbase::write_file(thematic_datasets_variables, 
		file.path(OUTDIR, "thematic_datasets_variables.rds"))
	vbase::write_file(head_var_children, file.path(OUTDIR, "head_var_children.rds"))
	vbase::write_file(head_var_parents, file.path(OUTDIR, "head_var_parents.rds"))
	vbase::write_file(df_dataset_selection, file.path(OUTDIR, "dataset_selection.rds"))
	vbase::write_file(df_selection, file.path(OUTDIR, "selection.rds"))
	vbase::write_file(merge_scores, file.path(OUTDIR, "merge_scores.rds"))
	return(invisible(NULL))
}

prep_selection <- function(variables, methodology, ROOT_DIR, cb_section, datasets, units) {
	DIR <- file.path(ROOT_DIR, "unit_data")
	# Selectable variables are these minus those that disappear.
	# New variables should always already exist in variables table!
	variables %<>% dplyr::filter(active, cb_show)

	# Sort and remove non-desired combinations
	methodology %<>% 
		dplyr::arrange(unit_tag, dataset_tag) %>%
		dplyr::filter(show)


	# Which ones disappear (per output unit)?
	df_from_files <- lapply(1:nrow(methodology), function(i, variables, DIR) {
		meth <- methodology[i, ]
		# print(i)
		vars <- variables %>% 
			dplyr::arrange(variable_id) %>%
			dplyr::filter(dataset_id %in% c(meth$dataset_id),
				!grepl("^u_", tag_long)) %$% tag_long

		ll <- file.path(DIR, meth$unit_tag, paste0(vars, ".rds"))
		# Remove those that do not have result
		vars <- vars[file.exists(ll)]
	
		if (length(vars) == 0) {
			print(paste0("No variables for unit: ", meth$unit_tag, ":: dataset ::", meth$dataset_tag))
			return(NULL)
		}

		data.frame(
			unit_tag = meth$unit_tag,
			dataset_tag = meth$dataset_tag,
			tag_long = vars)
	}, variables = variables, DIR = DIR) %>% dplyr::bind_rows()

	# Check unique cb_sections
	check_rows <- 
		cb_section %>%
		dplyr::group_by(dataset_tag, cb_section_tag) %>%
		dplyr::filter(dplyr::n() > 1)  %>%
		dplyr::arrange(dataset_tag, cb_section_tag)
	stopifnot(nrow(check_rows) == 0L)

	outdf <-
		df_from_files %>%
		# Add variable names and cb_sections
		dplyr::left_join(dplyr::select(variables, tag_long, variable_name = name, tag, cb_section), 
			by = c("tag_long")) %>%
		# Add codebook section identifiers and names
		dplyr::left_join(dplyr::select(cb_section, cb_section_tag, dataset_tag, cb_section_name),
			by = c("dataset_tag", "cb_section" = "cb_section_tag")) %>%
		# Add dataset names
		dplyr::left_join(dplyr::select(datasets, dataset_tag = tag, dataset_name = name),
			by = c("dataset_tag")) %>%
		# Add unit names
		dplyr::left_join(dplyr::select(units, unit_tag, unit_name),
			by = c("unit_tag")) %>%
		dplyr::mutate(select_id = 1:nrow(.)) %>%
		dplyr::select(select_id, unit_tag, unit_name, dataset_tag, dataset_name, cb_section, cb_section_name,
			tag, tag_long, variable_name)

	# Last checks!
	stopifnot(!is.na(outdf$unit_name))
	stopifnot(!is.na(outdf$dataset_name))
	stopifnot(!is.na(outdf$cb_section))
	stopifnot(!is.na(outdf$cb_section_name))
	stopifnot(!is.na(outdf$variable_name))

	# What combinations exist in variables table but not in cb_section table?
	# outdf %>%
	# 	select(dataset_tag, cb_section) %>%
	# 	anti_join(select(cb_section, cb_section_tag, dataset_tag),
	# 		by = c("dataset_tag", "cb_section" = "cb_section_tag")) %>% 
	# 	distinct %>% view
	# 	write_file("~/cb_sections.csv")
	return(outdf)
}

prep_dataset_selection <- function(methodology, datasets, units) {
	# Table for dataset selection in download interface---------------------------
	df_dataset_selection <- methodology %>%
		dplyr::arrange(dataset_tag, unit_tag) %>%
		dplyr::select(dataset_tag, unit_tag, show) %>%
		dplyr::filter(show) %>%
		dplyr::select(-show) %>%
		dplyr::left_join(dplyr::select(datasets, dataset_tag = tag, dataset_name = name,
			default_unit), 
			by = "dataset_tag") %>%
		dplyr::left_join(dplyr::select(units, unit_tag, unit_name), 
			by = "unit_tag") %>%
		dplyr::select(dataset_tag, dataset_name, unit_tag, unit_name, default_unit) %>%
		dplyr::arrange(dataset_tag) %>%
		dplyr::mutate(dataset_selection_id = 1:nrow(.)) %>%
		dplyr::select(dataset_selection_id, dplyr::everything())
	return(df_dataset_selection)
}







#' @title Prepare references for codebook and download interface
#' @description This function prepares the references for the codebook and the download interface.
#' It downloads and prepares reference files.
#' @export
prepare_autogen <- function() {
	download_refs()
	copy_static_refs()
	prepare_refs()
}